package com.hanfu.payment.center.dao;

import com.hanfu.payment.center.model.HfStone;
import com.hanfu.payment.center.model.HfStoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfStoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    long countByExample(HfStoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    int deleteByExample(HfStoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    int insert(HfStone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    int insertSelective(HfStone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    List<HfStone> selectByExample(HfStoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    HfStone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfStone record, @Param("example") HfStoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    int updateByExample(@Param("record") HfStone record, @Param("example") HfStoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    int updateByPrimaryKeySelective(HfStone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone
     *
     * @mbg.generated Wed Aug 05 17:42:36 CST 2020
     */
    int updateByPrimaryKey(HfStone record);
}