package com.hanfu.order.center.dao;

import com.hanfu.order.center.model.DiscountCouponOrder;
import com.hanfu.order.center.model.DiscountCouponOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiscountCouponOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    long countByExample(DiscountCouponOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    int deleteByExample(DiscountCouponOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    int insert(DiscountCouponOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    int insertSelective(DiscountCouponOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    List<DiscountCouponOrder> selectByExample(DiscountCouponOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    DiscountCouponOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") DiscountCouponOrder record, @Param("example") DiscountCouponOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    int updateByExample(@Param("record") DiscountCouponOrder record, @Param("example") DiscountCouponOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    int updateByPrimaryKeySelective(DiscountCouponOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_coupon_order
     *
     * @mbg.generated Sat Apr 11 09:42:13 CST 2020
     */
    int updateByPrimaryKey(DiscountCouponOrder record);
}