package com.hanfu.order.center.dao;

import com.hanfu.order.center.model.HfActivityCount;
import com.hanfu.order.center.model.HfActivityCountExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HfActivityCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    long countByExample(HfActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    int deleteByExample(HfActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    int insert(HfActivityCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    int insertSelective(HfActivityCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    List<HfActivityCount> selectByExample(HfActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    HfActivityCount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfActivityCount record, @Param("example") HfActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    int updateByExample(@Param("record") HfActivityCount record, @Param("example") HfActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    int updateByPrimaryKeySelective(HfActivityCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_activity_count
     *
     * @mbg.generated Thu Apr 02 13:23:59 CST 2020
     */
    int updateByPrimaryKey(HfActivityCount record);
}