package com.hanfu.dichan.center.dao;

import com.hanfu.dichan.center.model.DcEvaluatePicture;
import com.hanfu.dichan.center.model.DcEvaluatePictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcEvaluatePictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    long countByExample(DcEvaluatePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    int deleteByExample(DcEvaluatePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    int insert(DcEvaluatePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    int insertSelective(DcEvaluatePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    List<DcEvaluatePicture> selectByExample(DcEvaluatePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    DcEvaluatePicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") DcEvaluatePicture record, @Param("example") DcEvaluatePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    int updateByExample(@Param("record") DcEvaluatePicture record, @Param("example") DcEvaluatePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    int updateByPrimaryKeySelective(DcEvaluatePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_evaluate_picture
     *
     * @mbg.generated Fri Jul 10 16:00:27 CST 2020
     */
    int updateByPrimaryKey(DcEvaluatePicture record);
}