package com.hanfu.dichan.center.dao;

import com.hanfu.dichan.center.model.DcFileDesc;
import com.hanfu.dichan.center.model.DcFileDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcFileDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    long countByExample(DcFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    int deleteByExample(DcFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    int insert(DcFileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    int insertSelective(DcFileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    List<DcFileDesc> selectByExample(DcFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    DcFileDesc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") DcFileDesc record, @Param("example") DcFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    int updateByExample(@Param("record") DcFileDesc record, @Param("example") DcFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    int updateByPrimaryKeySelective(DcFileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_file_desc
     *
     * @mbg.generated Tue Jul 07 10:01:16 CST 2020
     */
    int updateByPrimaryKey(DcFileDesc record);
}