package com.hanfu.dichan.center.dao;

import com.hanfu.dichan.center.model.DcProject;
import com.hanfu.dichan.center.model.DcProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    long countByExample(DcProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    int deleteByExample(DcProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    int insert(DcProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    int insertSelective(DcProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    List<DcProject> selectByExample(DcProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    DcProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") DcProject record, @Param("example") DcProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    int updateByExample(@Param("record") DcProject record, @Param("example") DcProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    int updateByPrimaryKeySelective(DcProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_project
     *
     * @mbg.generated Tue Jul 07 09:40:36 CST 2020
     */
    int updateByPrimaryKey(DcProject record);
}