package com.hanfu.dichan.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class DcCompany implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.id
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.company_name
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.site
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private String site;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.phone
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.email
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.web_url
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private String webUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.company_code
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.create_date
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.modify_date
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_company.id_deleted
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private Byte idDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_company
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.id
     *
     * @return the value of dc_company.id
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.id
     *
     * @param id the value for dc_company.id
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.company_name
     *
     * @return the value of dc_company.company_name
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.company_name
     *
     * @param companyName the value for dc_company.company_name
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.site
     *
     * @return the value of dc_company.site
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.site
     *
     * @param site the value for dc_company.site
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.phone
     *
     * @return the value of dc_company.phone
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.phone
     *
     * @param phone the value for dc_company.phone
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.email
     *
     * @return the value of dc_company.email
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.email
     *
     * @param email the value for dc_company.email
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.web_url
     *
     * @return the value of dc_company.web_url
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.web_url
     *
     * @param webUrl the value for dc_company.web_url
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl == null ? null : webUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.company_code
     *
     * @return the value of dc_company.company_code
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.company_code
     *
     * @param companyCode the value for dc_company.company_code
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.create_date
     *
     * @return the value of dc_company.create_date
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.create_date
     *
     * @param createDate the value for dc_company.create_date
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.modify_date
     *
     * @return the value of dc_company.modify_date
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.modify_date
     *
     * @param modifyDate the value for dc_company.modify_date
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_company.id_deleted
     *
     * @return the value of dc_company.id_deleted
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public Byte getIdDeleted() {
        return idDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_company.id_deleted
     *
     * @param idDeleted the value for dc_company.id_deleted
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    public void setIdDeleted(Byte idDeleted) {
        this.idDeleted = idDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_company
     *
     * @mbg.generated Mon Jul 06 14:04:21 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyName=").append(companyName);
        sb.append(", site=").append(site);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", webUrl=").append(webUrl);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", idDeleted=").append(idDeleted);
        sb.append("]");
        return sb.toString();
    }
}