package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.DistributionRecord;
import com.hanfu.product.center.model.DistributionRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DistributionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    long countByExample(DistributionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    int deleteByExample(DistributionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    int insert(DistributionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    int insertSelective(DistributionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    List<DistributionRecord> selectByExample(DistributionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    DistributionRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") DistributionRecord record, @Param("example") DistributionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    int updateByExample(@Param("record") DistributionRecord record, @Param("example") DistributionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    int updateByPrimaryKeySelective(DistributionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    int updateByPrimaryKey(DistributionRecord record);
}