package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.EvaluateUserRecord;
import com.hanfu.product.center.model.EvaluateUserRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvaluateUserRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    long countByExample(EvaluateUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    int deleteByExample(EvaluateUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    int insert(EvaluateUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    int insertSelective(EvaluateUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    List<EvaluateUserRecord> selectByExample(EvaluateUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    EvaluateUserRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") EvaluateUserRecord record, @Param("example") EvaluateUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    int updateByExample(@Param("record") EvaluateUserRecord record, @Param("example") EvaluateUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    int updateByPrimaryKeySelective(EvaluateUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_user_record
     *
     * @mbg.generated Wed Apr 29 10:45:55 CST 2020
     */
    int updateByPrimaryKey(EvaluateUserRecord record);
}