package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.EvluateInstancePicture;
import com.hanfu.product.center.model.EvluateInstancePictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvluateInstancePictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    long countByExample(EvluateInstancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    int deleteByExample(EvluateInstancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    int insert(EvluateInstancePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    int insertSelective(EvluateInstancePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    List<EvluateInstancePicture> selectByExample(EvluateInstancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    EvluateInstancePicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") EvluateInstancePicture record, @Param("example") EvluateInstancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    int updateByExample(@Param("record") EvluateInstancePicture record, @Param("example") EvluateInstancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    int updateByPrimaryKeySelective(EvluateInstancePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evluate_instance_picture
     *
     * @mbg.generated Tue Apr 14 17:12:55 CST 2020
     */
    int updateByPrimaryKey(EvluateInstancePicture record);
}