package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.hfCouponsStrategy;
import com.hanfu.product.center.model.hfCouponsStrategyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface hfCouponsStrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    long countByExample(hfCouponsStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    int deleteByExample(hfCouponsStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    int insert(hfCouponsStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    int insertSelective(hfCouponsStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    List<hfCouponsStrategy> selectByExample(hfCouponsStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    hfCouponsStrategy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") hfCouponsStrategy record, @Param("example") hfCouponsStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    int updateByExample(@Param("record") hfCouponsStrategy record, @Param("example") hfCouponsStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    int updateByPrimaryKeySelective(hfCouponsStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_coupons_strategy
     *
     * @mbg.generated Mon Feb 10 09:00:31 CST 2020
     */
    int updateByPrimaryKey(hfCouponsStrategy record);
}