package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.HfInStorage;
import com.hanfu.product.center.model.HfInStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfInStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    long countByExample(HfInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    int deleteByExample(HfInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    int insert(HfInStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    int insertSelective(HfInStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    List<HfInStorage> selectByExample(HfInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    HfInStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfInStorage record, @Param("example") HfInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    int updateByExample(@Param("record") HfInStorage record, @Param("example") HfInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    int updateByPrimaryKeySelective(HfInStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    int updateByPrimaryKey(HfInStorage record);
}