package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.HfStoneConcern;
import com.hanfu.product.center.model.HfStoneConcernExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfStoneConcernMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    long countByExample(HfStoneConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    int deleteByExample(HfStoneConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    int insert(HfStoneConcern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    int insertSelective(HfStoneConcern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    List<HfStoneConcern> selectByExample(HfStoneConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    HfStoneConcern selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfStoneConcern record, @Param("example") HfStoneConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    int updateByExample(@Param("record") HfStoneConcern record, @Param("example") HfStoneConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    int updateByPrimaryKeySelective(HfStoneConcern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_stone_concern
     *
     * @mbg.generated Mon Apr 06 12:20:12 CST 2020
     */
    int updateByPrimaryKey(HfStoneConcern record);
}