package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.HfVipOrder;
import com.hanfu.product.center.model.HfVipOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfVipOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    long countByExample(HfVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    int deleteByExample(HfVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    int insert(HfVipOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    int insertSelective(HfVipOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    List<HfVipOrder> selectByExample(HfVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    HfVipOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfVipOrder record, @Param("example") HfVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    int updateByExample(@Param("record") HfVipOrder record, @Param("example") HfVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    int updateByPrimaryKeySelective(HfVipOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip_order
     *
     * @mbg.generated Tue Dec 08 16:23:54 CST 2020
     */
    int updateByPrimaryKey(HfVipOrder record);
}