package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.StoneRespRecord;
import com.hanfu.product.center.model.StoneRespRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoneRespRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    long countByExample(StoneRespRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    int deleteByExample(StoneRespRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    int insert(StoneRespRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    int insertSelective(StoneRespRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    List<StoneRespRecord> selectByExample(StoneRespRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    StoneRespRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") StoneRespRecord record, @Param("example") StoneRespRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    int updateByExample(@Param("record") StoneRespRecord record, @Param("example") StoneRespRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    int updateByPrimaryKeySelective(StoneRespRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_resp_record
     *
     * @mbg.generated Fri May 08 11:34:44 CST 2020
     */
    int updateByPrimaryKey(StoneRespRecord record);
}