package com.hanfu.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class DistributionRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.distribution_money
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private Integer distributionMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.stone_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private Integer stoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.Invitation_user_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private Integer invitationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.quilt_user_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private Integer quiltUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.dis_type
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private String disType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.dis_state
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private Integer disState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.order_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.create_date
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.modify_date
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_record.is_deleted
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.id
     *
     * @return the value of distribution_record.id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.id
     *
     * @param id the value for distribution_record.id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.distribution_money
     *
     * @return the value of distribution_record.distribution_money
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public Integer getDistributionMoney() {
        return distributionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.distribution_money
     *
     * @param distributionMoney the value for distribution_record.distribution_money
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setDistributionMoney(Integer distributionMoney) {
        this.distributionMoney = distributionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.stone_id
     *
     * @return the value of distribution_record.stone_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public Integer getStoneId() {
        return stoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.stone_id
     *
     * @param stoneId the value for distribution_record.stone_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setStoneId(Integer stoneId) {
        this.stoneId = stoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.Invitation_user_id
     *
     * @return the value of distribution_record.Invitation_user_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public Integer getInvitationUserId() {
        return invitationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.Invitation_user_id
     *
     * @param invitationUserId the value for distribution_record.Invitation_user_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setInvitationUserId(Integer invitationUserId) {
        this.invitationUserId = invitationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.quilt_user_id
     *
     * @return the value of distribution_record.quilt_user_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public Integer getQuiltUserId() {
        return quiltUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.quilt_user_id
     *
     * @param quiltUserId the value for distribution_record.quilt_user_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setQuiltUserId(Integer quiltUserId) {
        this.quiltUserId = quiltUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.dis_type
     *
     * @return the value of distribution_record.dis_type
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public String getDisType() {
        return disType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.dis_type
     *
     * @param disType the value for distribution_record.dis_type
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setDisType(String disType) {
        this.disType = disType == null ? null : disType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.dis_state
     *
     * @return the value of distribution_record.dis_state
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public Integer getDisState() {
        return disState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.dis_state
     *
     * @param disState the value for distribution_record.dis_state
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setDisState(Integer disState) {
        this.disState = disState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.order_id
     *
     * @return the value of distribution_record.order_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.order_id
     *
     * @param orderId the value for distribution_record.order_id
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.create_date
     *
     * @return the value of distribution_record.create_date
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.create_date
     *
     * @param createDate the value for distribution_record.create_date
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.modify_date
     *
     * @return the value of distribution_record.modify_date
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.modify_date
     *
     * @param modifyDate the value for distribution_record.modify_date
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_record.is_deleted
     *
     * @return the value of distribution_record.is_deleted
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_record.is_deleted
     *
     * @param isDeleted the value for distribution_record.is_deleted
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_record
     *
     * @mbg.generated Wed Apr 22 14:30:47 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", distributionMoney=").append(distributionMoney);
        sb.append(", stoneId=").append(stoneId);
        sb.append(", invitationUserId=").append(invitationUserId);
        sb.append(", quiltUserId=").append(quiltUserId);
        sb.append(", disType=").append(disType);
        sb.append(", disState=").append(disState);
        sb.append(", orderId=").append(orderId);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}