package com.hanfu.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class EvaluatePicture implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate_picture.id
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate_picture.hf_name
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private String hfName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate_picture.evaluate
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private Integer evaluate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate_picture.hf_desc
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private String hfDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate_picture.file_id
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate_picture.create_time
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate_picture.modifiey_time
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private LocalDateTime modifieyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate_picture.is_deleted
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table evaluate_picture
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate_picture.id
     *
     * @return the value of evaluate_picture.id
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate_picture.id
     *
     * @param id the value for evaluate_picture.id
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate_picture.hf_name
     *
     * @return the value of evaluate_picture.hf_name
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public String getHfName() {
        return hfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate_picture.hf_name
     *
     * @param hfName the value for evaluate_picture.hf_name
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public void setHfName(String hfName) {
        this.hfName = hfName == null ? null : hfName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate_picture.evaluate
     *
     * @return the value of evaluate_picture.evaluate
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public Integer getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate_picture.evaluate
     *
     * @param evaluate the value for evaluate_picture.evaluate
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public void setEvaluate(Integer evaluate) {
        this.evaluate = evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate_picture.hf_desc
     *
     * @return the value of evaluate_picture.hf_desc
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public String getHfDesc() {
        return hfDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate_picture.hf_desc
     *
     * @param hfDesc the value for evaluate_picture.hf_desc
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public void setHfDesc(String hfDesc) {
        this.hfDesc = hfDesc == null ? null : hfDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate_picture.file_id
     *
     * @return the value of evaluate_picture.file_id
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate_picture.file_id
     *
     * @param fileId the value for evaluate_picture.file_id
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate_picture.create_time
     *
     * @return the value of evaluate_picture.create_time
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate_picture.create_time
     *
     * @param createTime the value for evaluate_picture.create_time
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate_picture.modifiey_time
     *
     * @return the value of evaluate_picture.modifiey_time
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public LocalDateTime getModifieyTime() {
        return modifieyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate_picture.modifiey_time
     *
     * @param modifieyTime the value for evaluate_picture.modifiey_time
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public void setModifieyTime(LocalDateTime modifieyTime) {
        this.modifieyTime = modifieyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate_picture.is_deleted
     *
     * @return the value of evaluate_picture.is_deleted
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate_picture.is_deleted
     *
     * @param isDeleted the value for evaluate_picture.is_deleted
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate_picture
     *
     * @mbg.generated Tue Apr 14 15:24:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", hfName=").append(hfName);
        sb.append(", evaluate=").append(evaluate);
        sb.append(", hfDesc=").append(hfDesc);
        sb.append(", fileId=").append(fileId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifieyTime=").append(modifieyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}