package com.hanfu.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HfGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_goods.id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_goods.instance_id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private Integer instanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_goods.quantity
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_goods.spec_desc
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private String specDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_goods.price_id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private Integer priceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_goods.create_time
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_goods.modify_time
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_goods.is_deleted
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hf_goods
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_goods.id
     *
     * @return the value of hf_goods.id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_goods.id
     *
     * @param id the value for hf_goods.id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_goods.instance_id
     *
     * @return the value of hf_goods.instance_id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public Integer getInstanceId() {
        return instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_goods.instance_id
     *
     * @param instanceId the value for hf_goods.instance_id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public void setInstanceId(Integer instanceId) {
        this.instanceId = instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_goods.quantity
     *
     * @return the value of hf_goods.quantity
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_goods.quantity
     *
     * @param quantity the value for hf_goods.quantity
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_goods.spec_desc
     *
     * @return the value of hf_goods.spec_desc
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public String getSpecDesc() {
        return specDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_goods.spec_desc
     *
     * @param specDesc the value for hf_goods.spec_desc
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public void setSpecDesc(String specDesc) {
        this.specDesc = specDesc == null ? null : specDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_goods.price_id
     *
     * @return the value of hf_goods.price_id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public Integer getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_goods.price_id
     *
     * @param priceId the value for hf_goods.price_id
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public void setPriceId(Integer priceId) {
        this.priceId = priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_goods.create_time
     *
     * @return the value of hf_goods.create_time
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_goods.create_time
     *
     * @param createTime the value for hf_goods.create_time
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_goods.modify_time
     *
     * @return the value of hf_goods.modify_time
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_goods.modify_time
     *
     * @param modifyTime the value for hf_goods.modify_time
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_goods.is_deleted
     *
     * @return the value of hf_goods.is_deleted
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_goods.is_deleted
     *
     * @param isDeleted the value for hf_goods.is_deleted
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_goods
     *
     * @mbg.generated Tue Sep 24 21:59:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", instanceId=").append(instanceId);
        sb.append(", quantity=").append(quantity);
        sb.append(", specDesc=").append(specDesc);
        sb.append(", priceId=").append(priceId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}