package com.hanfu.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HfInStorage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.apply_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Integer applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.boss_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Integer bossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.data_type
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.type
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.produc_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Integer producId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.good_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.quantity
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.user_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.stone_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Integer stoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.create_time
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.modify_time
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_in_storage.is_deleted
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hf_in_storage
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.id
     *
     * @return the value of hf_in_storage.id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.id
     *
     * @param id the value for hf_in_storage.id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.apply_id
     *
     * @return the value of hf_in_storage.apply_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.apply_id
     *
     * @param applyId the value for hf_in_storage.apply_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.boss_id
     *
     * @return the value of hf_in_storage.boss_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Integer getBossId() {
        return bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.boss_id
     *
     * @param bossId the value for hf_in_storage.boss_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setBossId(Integer bossId) {
        this.bossId = bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.data_type
     *
     * @return the value of hf_in_storage.data_type
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.data_type
     *
     * @param dataType the value for hf_in_storage.data_type
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.type
     *
     * @return the value of hf_in_storage.type
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.type
     *
     * @param type the value for hf_in_storage.type
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.produc_id
     *
     * @return the value of hf_in_storage.produc_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Integer getProducId() {
        return producId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.produc_id
     *
     * @param producId the value for hf_in_storage.produc_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setProducId(Integer producId) {
        this.producId = producId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.good_id
     *
     * @return the value of hf_in_storage.good_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.good_id
     *
     * @param goodId the value for hf_in_storage.good_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.quantity
     *
     * @return the value of hf_in_storage.quantity
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.quantity
     *
     * @param quantity the value for hf_in_storage.quantity
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.user_id
     *
     * @return the value of hf_in_storage.user_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.user_id
     *
     * @param userId the value for hf_in_storage.user_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.stone_id
     *
     * @return the value of hf_in_storage.stone_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Integer getStoneId() {
        return stoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.stone_id
     *
     * @param stoneId the value for hf_in_storage.stone_id
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setStoneId(Integer stoneId) {
        this.stoneId = stoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.create_time
     *
     * @return the value of hf_in_storage.create_time
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.create_time
     *
     * @param createTime the value for hf_in_storage.create_time
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.modify_time
     *
     * @return the value of hf_in_storage.modify_time
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.modify_time
     *
     * @param modifyTime the value for hf_in_storage.modify_time
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_in_storage.is_deleted
     *
     * @return the value of hf_in_storage.is_deleted
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_in_storage.is_deleted
     *
     * @param isDeleted the value for hf_in_storage.is_deleted
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_in_storage
     *
     * @mbg.generated Tue May 12 11:17:59 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", applyId=").append(applyId);
        sb.append(", bossId=").append(bossId);
        sb.append(", dataType=").append(dataType);
        sb.append(", type=").append(type);
        sb.append(", producId=").append(producId);
        sb.append(", goodId=").append(goodId);
        sb.append(", quantity=").append(quantity);
        sb.append(", userId=").append(userId);
        sb.append(", stoneId=").append(stoneId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}