package com.hanfu.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class WarehouseApplyGood implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.good_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.status
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.product_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.user_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.warehouse_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer warehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.boss_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer bossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.quantity
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.apply_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Integer applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.create_time
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.modify_time
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_apply_good.is_deleted
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse_apply_good
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.id
     *
     * @return the value of warehouse_apply_good.id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.id
     *
     * @param id the value for warehouse_apply_good.id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.good_id
     *
     * @return the value of warehouse_apply_good.good_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.good_id
     *
     * @param goodId the value for warehouse_apply_good.good_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.status
     *
     * @return the value of warehouse_apply_good.status
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.status
     *
     * @param status the value for warehouse_apply_good.status
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.product_id
     *
     * @return the value of warehouse_apply_good.product_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.product_id
     *
     * @param productId the value for warehouse_apply_good.product_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.user_id
     *
     * @return the value of warehouse_apply_good.user_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.user_id
     *
     * @param userId the value for warehouse_apply_good.user_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.warehouse_id
     *
     * @return the value of warehouse_apply_good.warehouse_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.warehouse_id
     *
     * @param warehouseId the value for warehouse_apply_good.warehouse_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.boss_id
     *
     * @return the value of warehouse_apply_good.boss_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getBossId() {
        return bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.boss_id
     *
     * @param bossId the value for warehouse_apply_good.boss_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setBossId(Integer bossId) {
        this.bossId = bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.quantity
     *
     * @return the value of warehouse_apply_good.quantity
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.quantity
     *
     * @param quantity the value for warehouse_apply_good.quantity
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.apply_id
     *
     * @return the value of warehouse_apply_good.apply_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.apply_id
     *
     * @param applyId the value for warehouse_apply_good.apply_id
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.create_time
     *
     * @return the value of warehouse_apply_good.create_time
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.create_time
     *
     * @param createTime the value for warehouse_apply_good.create_time
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.modify_time
     *
     * @return the value of warehouse_apply_good.modify_time
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.modify_time
     *
     * @param modifyTime the value for warehouse_apply_good.modify_time
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_apply_good.is_deleted
     *
     * @return the value of warehouse_apply_good.is_deleted
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_apply_good.is_deleted
     *
     * @param isDeleted the value for warehouse_apply_good.is_deleted
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_apply_good
     *
     * @mbg.generated Wed May 13 16:08:19 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodId=").append(goodId);
        sb.append(", status=").append(status);
        sb.append(", productId=").append(productId);
        sb.append(", userId=").append(userId);
        sb.append(", warehouseId=").append(warehouseId);
        sb.append(", bossId=").append(bossId);
        sb.append(", quantity=").append(quantity);
        sb.append(", applyId=").append(applyId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}