package com.hanfu.user.center.Jurisdiction.dao;

import com.hanfu.user.center.Jurisdiction.model.AccountRoles;
import com.hanfu.user.center.Jurisdiction.model.AccountRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    long countByExample(AccountRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    int deleteByExample(AccountRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    int insert(AccountRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    int insertSelective(AccountRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    List<AccountRoles> selectByExample(AccountRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    AccountRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccountRoles record, @Param("example") AccountRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    int updateByExample(@Param("record") AccountRoles record, @Param("example") AccountRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    int updateByPrimaryKeySelective(AccountRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Tue May 26 15:29:28 CST 2020
     */
    int updateByPrimaryKey(AccountRoles record);
}