package com.hanfu.payment.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class AccountRoles implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_roles.id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_roles.roles_id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    private Integer rolesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_roles.account_id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_roles.create_time
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_roles.modify_time
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_roles.is_deleted
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_roles
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_roles.id
     *
     * @return the value of account_roles.id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_roles.id
     *
     * @param id the value for account_roles.id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_roles.roles_id
     *
     * @return the value of account_roles.roles_id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public Integer getRolesId() {
        return rolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_roles.roles_id
     *
     * @param rolesId the value for account_roles.roles_id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public void setRolesId(Integer rolesId) {
        this.rolesId = rolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_roles.account_id
     *
     * @return the value of account_roles.account_id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_roles.account_id
     *
     * @param accountId the value for account_roles.account_id
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_roles.create_time
     *
     * @return the value of account_roles.create_time
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_roles.create_time
     *
     * @param createTime the value for account_roles.create_time
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_roles.modify_time
     *
     * @return the value of account_roles.modify_time
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_roles.modify_time
     *
     * @param modifyTime the value for account_roles.modify_time
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_roles.is_deleted
     *
     * @return the value of account_roles.is_deleted
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_roles.is_deleted
     *
     * @param isDeleted the value for account_roles.is_deleted
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_roles
     *
     * @mbg.generated Mon Jun 08 17:16:17 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rolesId=").append(rolesId);
        sb.append(", accountId=").append(accountId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}