package com.hanfu.payment.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class StoneBalance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.id
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.stone_id
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private Integer stoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.balance_type
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private String balanceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.stone_balance
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private Integer stoneBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.pay_method_type
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private String payMethodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.hf_remark
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private String hfRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.create_time
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.modify_time
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.last_modifier
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private String lastModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_balance.is_deleted
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stone_balance
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.id
     *
     * @return the value of stone_balance.id
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.id
     *
     * @param id the value for stone_balance.id
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.stone_id
     *
     * @return the value of stone_balance.stone_id
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public Integer getStoneId() {
        return stoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.stone_id
     *
     * @param stoneId the value for stone_balance.stone_id
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setStoneId(Integer stoneId) {
        this.stoneId = stoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.balance_type
     *
     * @return the value of stone_balance.balance_type
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public String getBalanceType() {
        return balanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.balance_type
     *
     * @param balanceType the value for stone_balance.balance_type
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setBalanceType(String balanceType) {
        this.balanceType = balanceType == null ? null : balanceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.stone_balance
     *
     * @return the value of stone_balance.stone_balance
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public Integer getStoneBalance() {
        return stoneBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.stone_balance
     *
     * @param stoneBalance the value for stone_balance.stone_balance
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setStoneBalance(Integer stoneBalance) {
        this.stoneBalance = stoneBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.pay_method_type
     *
     * @return the value of stone_balance.pay_method_type
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public String getPayMethodType() {
        return payMethodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.pay_method_type
     *
     * @param payMethodType the value for stone_balance.pay_method_type
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setPayMethodType(String payMethodType) {
        this.payMethodType = payMethodType == null ? null : payMethodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.hf_remark
     *
     * @return the value of stone_balance.hf_remark
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public String getHfRemark() {
        return hfRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.hf_remark
     *
     * @param hfRemark the value for stone_balance.hf_remark
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setHfRemark(String hfRemark) {
        this.hfRemark = hfRemark == null ? null : hfRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.create_time
     *
     * @return the value of stone_balance.create_time
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.create_time
     *
     * @param createTime the value for stone_balance.create_time
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.modify_time
     *
     * @return the value of stone_balance.modify_time
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.modify_time
     *
     * @param modifyTime the value for stone_balance.modify_time
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.last_modifier
     *
     * @return the value of stone_balance.last_modifier
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.last_modifier
     *
     * @param lastModifier the value for stone_balance.last_modifier
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_balance.is_deleted
     *
     * @return the value of stone_balance.is_deleted
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_balance.is_deleted
     *
     * @param isDeleted the value for stone_balance.is_deleted
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_balance
     *
     * @mbg.generated Tue Apr 21 10:17:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stoneId=").append(stoneId);
        sb.append(", balanceType=").append(balanceType);
        sb.append(", stoneBalance=").append(stoneBalance);
        sb.append(", payMethodType=").append(payMethodType);
        sb.append(", hfRemark=").append(hfRemark);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", lastModifier=").append(lastModifier);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}