package com.hanfu.user.center.dao;

import com.hanfu.user.center.model.ActivityAuth;
import com.hanfu.user.center.model.ActivityAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    long countByExample(ActivityAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    int deleteByExample(ActivityAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    int insert(ActivityAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    int insertSelective(ActivityAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    List<ActivityAuth> selectByExample(ActivityAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    ActivityAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") ActivityAuth record, @Param("example") ActivityAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    int updateByExample(@Param("record") ActivityAuth record, @Param("example") ActivityAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    int updateByPrimaryKeySelective(ActivityAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_auth
     *
     * @mbg.generated Thu Aug 27 09:49:35 CST 2020
     */
    int updateByPrimaryKey(ActivityAuth record);
}