package com.hanfu.user.center.dao;

import com.hanfu.user.center.model.HfMessageApply;
import com.hanfu.user.center.model.HfMessageApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfMessageApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    long countByExample(HfMessageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    int deleteByExample(HfMessageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    int insert(HfMessageApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    int insertSelective(HfMessageApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    List<HfMessageApply> selectByExample(HfMessageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    HfMessageApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfMessageApply record, @Param("example") HfMessageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    int updateByExample(@Param("record") HfMessageApply record, @Param("example") HfMessageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    int updateByPrimaryKeySelective(HfMessageApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_apply
     *
     * @mbg.generated Mon May 25 11:22:09 CST 2020
     */
    int updateByPrimaryKey(HfMessageApply record);
}