package com.hanfu.user.center.dao;

import com.hanfu.user.center.model.HfMessageInfo;
import com.hanfu.user.center.model.HfMessageInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfMessageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    long countByExample(HfMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    int deleteByExample(HfMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    int insert(HfMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    int insertSelective(HfMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    List<HfMessageInfo> selectByExample(HfMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    HfMessageInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfMessageInfo record, @Param("example") HfMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    int updateByExample(@Param("record") HfMessageInfo record, @Param("example") HfMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    int updateByPrimaryKeySelective(HfMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    int updateByPrimaryKey(HfMessageInfo record);
}