package com.hanfu.activity.center.dao;

import com.hanfu.activity.center.model.ActivityFileDesc;
import com.hanfu.activity.center.model.ActivityFileDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityFileDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    long countByExample(ActivityFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    int deleteByExample(ActivityFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    int insert(ActivityFileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    int insertSelective(ActivityFileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    List<ActivityFileDesc> selectByExample(ActivityFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    ActivityFileDesc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") ActivityFileDesc record, @Param("example") ActivityFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    int updateByExample(@Param("record") ActivityFileDesc record, @Param("example") ActivityFileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    int updateByPrimaryKeySelective(ActivityFileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_file_desc
     *
     * @mbg.generated Mon Aug 24 11:05:32 CST 2020
     */
    int updateByPrimaryKey(ActivityFileDesc record);
}