package com.hanfu.activity.center.dao;

import com.hanfu.activity.center.model.ActivitiStrategy;
import com.hanfu.activity.center.model.ActivitiStrategyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivitiStrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    long countByExample(ActivitiStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    int deleteByExample(ActivitiStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    int insert(ActivitiStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    int insertSelective(ActivitiStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    List<ActivitiStrategy> selectByExample(ActivitiStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    ActivitiStrategy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") ActivitiStrategy record, @Param("example") ActivitiStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    int updateByExample(@Param("record") ActivitiStrategy record, @Param("example") ActivitiStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    int updateByPrimaryKeySelective(ActivitiStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activiti_strategy
     *
     * @mbg.generated Fri Aug 28 11:29:54 CST 2020
     */
    int updateByPrimaryKey(ActivitiStrategy record);
}