package com.hanfu.activity.center.dao;

import com.hanfu.activity.center.model.RuleValueDesc;
import com.hanfu.activity.center.model.RuleValueDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuleValueDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    long countByExample(RuleValueDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    int deleteByExample(RuleValueDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    int insert(RuleValueDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    int insertSelective(RuleValueDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    List<RuleValueDesc> selectByExample(RuleValueDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    RuleValueDesc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") RuleValueDesc record, @Param("example") RuleValueDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    int updateByExample(@Param("record") RuleValueDesc record, @Param("example") RuleValueDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    int updateByPrimaryKeySelective(RuleValueDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_value_desc
     *
     * @mbg.generated Mon Nov 11 07:08:01 CST 2019
     */
    int updateByPrimaryKey(RuleValueDesc record);
}