server:
  port: 9999
wxapplet.config.weixinpay.notifyurl: http://localhost:9099/pay/weixin/callback

spring:
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://39.98.126.20:3306/user_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: hanfu_admin
    password: Davin1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select now()
      idle-timeout: 300
      auto-commit: true
  redis:
    database: 0
    host: 47.105.72.216
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 16
        max-idle: 4
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
        keep-alive: 3600s

info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false

logging:
  file: ./logs/king-words.log

mybatis:
  mapper-locations:
    - mappers/*.xml
    - manual-mappers/*.xml

#服务器域名地址
  server.service-domain: http://127.0.0.1:9099

  ##支付宝支付
  pay.alipay.gatewayUrl: "https://openapi.alipaydev.com/gateway.do"
  pay.alipay.appid: "2021000116677309"
  pay.alipay.app-private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAZjCbEeW9Oodg47+SvzibakyGe2cMvHVhdRn7g4Kw4XPMAmhCmAj+VRT0Mmdgf5ziQckFWaMngM3ZfmlJ6CV/JYTDCeTI9Iomi2VgLScGvKViYVv4GYrovwHQmYIucmHNJoPKGRUgrHzJzJewNJUQ9KyzydUNFF5lLNoHxvvNcLqzqluL3+VFKlnYpoZHcizc37sk2+usE+lKgvTWwbKTsNCEs1qDNrXTeR+Ik1AidO/BL6q9nU/49ZajA7ZUYKtJpmc/N+9fU8tmfJmhbdmmNMUrmrrukhYZ9CSu9y+P6U7AfMLJkdcPneMjh9ki488G4wPCSe1r1LR2/r5OljxtAgMBAAECggEAU0Bkq9T0ugrHZY9m59LCZc17S32+O26YxBDtqz1eobcMaixofNhYm+So6nmc7c6KTgT1PNFqnb9IU2I1oPtIrlnHtrVjP+lAlikfNpyTFIEwdv910kcLKmbsHB0wjXSFCUYvJJXx5G9+l7tlr6MxFWMqD6m3/K7hoZnkxhS+BEiQWdWRFCHiR5IXjCRn8E3sKhIEitcYQPkTgLsW87ARzTvSWQF/FrIlUJT9Gal3Fj3TBjcvHLUoiIOuGwjNsASFPF+Pd/5aE2e5kQnvReh6hKVy67jb2Y499IoYFsu57PjVNDRdGKmbm8+xB0/YWbdQbnFnRFupGOgpqWe2z1nXwQKBgQDx5+nVdL9q6yN/RiLiWV2h2xM5ZW0F7Xtr3ylqdyXGD2DNkga3PbyOwh0kGR5XY660e2HgVOeqf5rLDndRbPTo89lWtEaOocGRictWXVc7fDwicySF53/V6AzYSyV5GwMrh2qTkL1eIjIXaDyVtnB1JH0g+RXL4maRAgGupaUd6QKBgQDLm98L3JD0wCRKi+gUMFMnLoTlS2p20JWYytGN2d4QQPQGlmpW5cZzz/94zXIKPjcnP9yn6DqJffBNUOy6egZMKHCkpp9j3b8sgzwskon8DqLu3YxmgyS+TRf8mPAzbRepFyZbqe/3rYf9bXg5GadrhrLkfDozzaFRpS6/CQrD5QKBgHtiMYd5U8TiCCn7iQFwWWybw/Nrgy8Z0PDVU1eFTBP4dgSELb6603jxE1H9Kdei9VIC+IomZD83dKmLSFqUu1oyPjGWI8LOSF/GK5tyYnLpy/Y6Sm+uAysEf8C2m3doyrYiDL8VfTENOgVsWjJ2amelY9k0kuR6JpxhrJ/6xvw5AoGBAI2ihz0EGN34zwYAXte0ahOme5HZrVyranUYGT+4342k8VunxJ9gRXWIqilJmNvhPZKTDRbMJ/Q+5CuUcKije7/8nacbtWLN/U+klvZWlZ/+On85JJKnBadPj7EKXoUXjU71qJw5EZHUZ/X18Zye6OSWldj1RbOFhoN6CZOgYZm1AoGAP8dbH+UbL14AGEbR/mAN4yM0EyqwpQ992OB0C7G7A9mZ5kHPChf7DpdJKxhk5Qkm8QS1Sf5UnqR9xqSWGWkyXUJ9TqSVW0bxZoPnTujCL3ztr/S2GGqieKe41b5Q3VWNIkEQSUC/MfsR5k1HGDf02PXDm5GdjIELHnpLp1K4bsI="
  pay.alipay.alipay-public-key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIgHnOn7LLILlKETd6BFRJ0GqgS2Y3mn1wMQmyh9zEyWlz5p1zrahRahbXAfCfSqshSNfqOmAQzSHRVjCqjsAw1jyqrXaPdKBmr90DIpIxmIyKXv4GGAkPyJ/6FTFY99uhpiq0qadD/uSzQsefWo0aTvP/65zi3eof7TcZ32oWpwIDAQAB"
  #支付成功的异步通知回调接口
  pay.alipay.notify-url: ${server.service-domain}/api/alipay/notify
