package com.hanfu.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HfMessageInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_message_info.id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_message_info.boss_id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private Integer bossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_message_info.access_key_id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private String accessKeyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_message_info.access_key_secret
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private String accessKeySecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_message_info.sign_name
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private String signName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_message_info.create_time
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_message_info.modify_time
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_message_info.is_deleted
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_message_info.id
     *
     * @return the value of hf_message_info.id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_message_info.id
     *
     * @param id the value for hf_message_info.id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_message_info.boss_id
     *
     * @return the value of hf_message_info.boss_id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public Integer getBossId() {
        return bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_message_info.boss_id
     *
     * @param bossId the value for hf_message_info.boss_id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public void setBossId(Integer bossId) {
        this.bossId = bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_message_info.access_key_id
     *
     * @return the value of hf_message_info.access_key_id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public String getAccessKeyId() {
        return accessKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_message_info.access_key_id
     *
     * @param accessKeyId the value for hf_message_info.access_key_id
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public void setAccessKeyId(String accessKeyId) {
        this.accessKeyId = accessKeyId == null ? null : accessKeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_message_info.access_key_secret
     *
     * @return the value of hf_message_info.access_key_secret
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public String getAccessKeySecret() {
        return accessKeySecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_message_info.access_key_secret
     *
     * @param accessKeySecret the value for hf_message_info.access_key_secret
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public void setAccessKeySecret(String accessKeySecret) {
        this.accessKeySecret = accessKeySecret == null ? null : accessKeySecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_message_info.sign_name
     *
     * @return the value of hf_message_info.sign_name
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public String getSignName() {
        return signName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_message_info.sign_name
     *
     * @param signName the value for hf_message_info.sign_name
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public void setSignName(String signName) {
        this.signName = signName == null ? null : signName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_message_info.create_time
     *
     * @return the value of hf_message_info.create_time
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_message_info.create_time
     *
     * @param createTime the value for hf_message_info.create_time
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_message_info.modify_time
     *
     * @return the value of hf_message_info.modify_time
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_message_info.modify_time
     *
     * @param modifyTime the value for hf_message_info.modify_time
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_message_info.is_deleted
     *
     * @return the value of hf_message_info.is_deleted
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_message_info.is_deleted
     *
     * @param isDeleted the value for hf_message_info.is_deleted
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_message_info
     *
     * @mbg.generated Fri May 22 14:36:55 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bossId=").append(bossId);
        sb.append(", accessKeyId=").append(accessKeyId);
        sb.append(", accessKeySecret=").append(accessKeySecret);
        sb.append(", signName=").append(signName);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}