package com.hanfu.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HfTemplateParam implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_template_param.id
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_template_param.type
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_template_param.param_name
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_template_param.create_time
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_template_param.modify_time
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_template_param.is_deleted
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hf_template_param
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_template_param.id
     *
     * @return the value of hf_template_param.id
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_template_param.id
     *
     * @param id the value for hf_template_param.id
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_template_param.type
     *
     * @return the value of hf_template_param.type
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_template_param.type
     *
     * @param type the value for hf_template_param.type
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_template_param.param_name
     *
     * @return the value of hf_template_param.param_name
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_template_param.param_name
     *
     * @param paramName the value for hf_template_param.param_name
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_template_param.create_time
     *
     * @return the value of hf_template_param.create_time
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_template_param.create_time
     *
     * @param createTime the value for hf_template_param.create_time
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_template_param.modify_time
     *
     * @return the value of hf_template_param.modify_time
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_template_param.modify_time
     *
     * @param modifyTime the value for hf_template_param.modify_time
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_template_param.is_deleted
     *
     * @return the value of hf_template_param.is_deleted
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_template_param.is_deleted
     *
     * @param isDeleted the value for hf_template_param.is_deleted
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_template_param
     *
     * @mbg.generated Tue May 26 11:49:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", paramName=").append(paramName);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}