package com.hanfu.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HfVip implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.vip_name
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private String vipName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.vip_day
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private Integer vipDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.vip_state
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private String vipState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.start_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private LocalDateTime startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.end_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.lable
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private String lable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.file_id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.vip_price
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private Integer vipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.boss_id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private Integer bossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.create_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.modify_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_vip.is_deleted
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hf_vip
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.id
     *
     * @return the value of hf_vip.id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.id
     *
     * @param id the value for hf_vip.id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.vip_name
     *
     * @return the value of hf_vip.vip_name
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public String getVipName() {
        return vipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.vip_name
     *
     * @param vipName the value for hf_vip.vip_name
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setVipName(String vipName) {
        this.vipName = vipName == null ? null : vipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.vip_day
     *
     * @return the value of hf_vip.vip_day
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public Integer getVipDay() {
        return vipDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.vip_day
     *
     * @param vipDay the value for hf_vip.vip_day
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setVipDay(Integer vipDay) {
        this.vipDay = vipDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.vip_state
     *
     * @return the value of hf_vip.vip_state
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public String getVipState() {
        return vipState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.vip_state
     *
     * @param vipState the value for hf_vip.vip_state
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setVipState(String vipState) {
        this.vipState = vipState == null ? null : vipState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.start_time
     *
     * @return the value of hf_vip.start_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public LocalDateTime getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.start_time
     *
     * @param startTime the value for hf_vip.start_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.end_time
     *
     * @return the value of hf_vip.end_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.end_time
     *
     * @param endTime the value for hf_vip.end_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.lable
     *
     * @return the value of hf_vip.lable
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public String getLable() {
        return lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.lable
     *
     * @param lable the value for hf_vip.lable
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setLable(String lable) {
        this.lable = lable == null ? null : lable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.file_id
     *
     * @return the value of hf_vip.file_id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.file_id
     *
     * @param fileId the value for hf_vip.file_id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.vip_price
     *
     * @return the value of hf_vip.vip_price
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public Integer getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.vip_price
     *
     * @param vipPrice the value for hf_vip.vip_price
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setVipPrice(Integer vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.boss_id
     *
     * @return the value of hf_vip.boss_id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public Integer getBossId() {
        return bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.boss_id
     *
     * @param bossId the value for hf_vip.boss_id
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setBossId(Integer bossId) {
        this.bossId = bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.create_time
     *
     * @return the value of hf_vip.create_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.create_time
     *
     * @param createTime the value for hf_vip.create_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.modify_time
     *
     * @return the value of hf_vip.modify_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.modify_time
     *
     * @param modifyTime the value for hf_vip.modify_time
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_vip.is_deleted
     *
     * @return the value of hf_vip.is_deleted
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_vip.is_deleted
     *
     * @param isDeleted the value for hf_vip.is_deleted
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_vip
     *
     * @mbg.generated Mon Dec 07 10:59:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", vipName=").append(vipName);
        sb.append(", vipDay=").append(vipDay);
        sb.append(", vipState=").append(vipState);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", lable=").append(lable);
        sb.append(", fileId=").append(fileId);
        sb.append(", vipPrice=").append(vipPrice);
        sb.append(", bossId=").append(bossId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}