package com.hanfu.user.center.Jurisdiction.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Department implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_name
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_code
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private String departmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_type
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private String departmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.account_id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.merchant_id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private Integer merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.is_jurisdiction
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private Integer isJurisdiction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.create_date
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.modify_date
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.is_deleted
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.last_modifier
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private String lastModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_name
     *
     * @return the value of department.department_name
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_name
     *
     * @param departmentName the value for department.department_name
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_code
     *
     * @return the value of department.department_code
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_code
     *
     * @param departmentCode the value for department.department_code
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_type
     *
     * @return the value of department.department_type
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public String getDepartmentType() {
        return departmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_type
     *
     * @param departmentType the value for department.department_type
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setDepartmentType(String departmentType) {
        this.departmentType = departmentType == null ? null : departmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.account_id
     *
     * @return the value of department.account_id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.account_id
     *
     * @param accountId the value for department.account_id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.merchant_id
     *
     * @return the value of department.merchant_id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.merchant_id
     *
     * @param merchantId the value for department.merchant_id
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.is_jurisdiction
     *
     * @return the value of department.is_jurisdiction
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public Integer getIsJurisdiction() {
        return isJurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.is_jurisdiction
     *
     * @param isJurisdiction the value for department.is_jurisdiction
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setIsJurisdiction(Integer isJurisdiction) {
        this.isJurisdiction = isJurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.create_date
     *
     * @return the value of department.create_date
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.create_date
     *
     * @param createDate the value for department.create_date
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.modify_date
     *
     * @return the value of department.modify_date
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.modify_date
     *
     * @param modifyDate the value for department.modify_date
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.is_deleted
     *
     * @return the value of department.is_deleted
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.is_deleted
     *
     * @param isDeleted the value for department.is_deleted
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.last_modifier
     *
     * @return the value of department.last_modifier
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.last_modifier
     *
     * @param lastModifier the value for department.last_modifier
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Tue May 26 11:27:10 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", departmentName=").append(departmentName);
        sb.append(", departmentCode=").append(departmentCode);
        sb.append(", departmentType=").append(departmentType);
        sb.append(", accountId=").append(accountId);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", isJurisdiction=").append(isJurisdiction);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", lastModifier=").append(lastModifier);
        sb.append("]");
        return sb.toString();
    }
}